In [1]:
pip install numpy

Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [40]:
import numpy as np

In [41]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [42]:
# shape
temperatures_w1.shape

(7,)

In [43]:
# datatype
temperatures_w1.dtype

dtype('float64')

In [44]:
# size
temperatures_w1.size

7

In [45]:
# Convert the temperatures_w1 from Celsius to Fahrenheit
fahrenheit = (temperatures_w1 * 9/5) + 32
fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [51]:
# maximum temperatures for the week.
temperatures_w1.max()

np.float64(26.1)

In [52]:
# minimum temperatures for the week.
temperatures_w1.min()

np.float64(20.8)

In [53]:
# mean temperatures for the week.
temperatures_w1.mean()

np.float64(23.542857142857144)

In [54]:
#temperatures for the first three days of the week.
temperatures_w1[:3]

array([22.5, 25.3, 20.8])

In [55]:
# temperatures for the weekend (last two days).
temperatures_w1[-2:]

array([24.8, 21.9])

In [56]:
# temperatures for the middle three days of the week.
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

In [57]:
# Create a 2D NumPy array named temperatures
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [64]:
# print the shape
temperatures.shape

(2, 7)

In [62]:
# data type
temperatures.dtype

dtype('float64')

In [63]:
# total number of elements
temperatures.size

14

In [65]:
# Extract the temperatures for each week and the weekends
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [21]:
temperatures[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [22]:
temperatures[0,-2:]

array([24.8, 21.9])

In [25]:
temperatures[1,-2:]

array([22.8, 20.1])

In [6]:
import pandas as pd

In [66]:
# Create a Pandas Series named marks
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [67]:
# Use the integer index position to access the mark of the 1st rank student.
(marks.iloc[0])

np.int64(95)

In [69]:
# Using retrieve the marks of the top 3 ranks by index labels.
marks.loc[['Rank1', 'Rank2', 'Rank3']]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [70]:
# Use the iloc accessor to retrieve the mark of the 3rd rank student.
marks.iloc[2]

np.int64(89)

In [71]:
# booleanmask to filter and retrieve the ranks >90
marks[marks > 90]

Rank1    95
Rank2    92
dtype: int64

In [72]:
# Modify the mark of the student with the 1st rank to 100.
marks.loc['Rank1'] = 100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [73]:
# Remove the entry corresponding to the last rank from the Series.
marks = marks.drop('Rank5')
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [74]:
# Compute the CGPA by dividing each mark in the Series by 10.
cgpa = marks / 10
cgpa

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [38]:
#Create a Pandas DataFrame named transactions 
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [30]:
# Display the transactions DataFrame and its basic information
transactions.head()
transactions.tail()
transactions.shape
transactions.columns
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [28]:
# Display only the 'ProductCategory' and 'Amount' columns.
transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     165
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
9     Electronics     400

In [27]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     165
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
9     Electronics  North     400

In [26]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [25]:
# Find the value counts for the 'ProductCategory' column.
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      2
Name: count, dtype: int64

In [31]:
# Find the unique values in the 'Region' column.
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [32]:
# Group by 'Region' and find the mean amount for each region.
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    165.0
West     190.0
Name: Amount, dtype: float64

In [34]:
#Modify the 'Amount' for the transaction with TransactionID 102 to 165.
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [35]:
#Add a new column 'Discount' by calculating 10% of the 'Amount'.
transactions['Discount'] = transactions['Amount'] * 0.10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [36]:
# Remove the row with TransactionID 109.
transactions.drop(
    transactions[transactions['TransactionID'] == 109].index,
    inplace=True
)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [37]:
# Delete the 'Discount' column from the DataFrame.
transactions.drop('Discount', axis=1, inplace=True)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400